version: '3.8'

services:
  serverless:
    build:
      context: .
    image: serverless-image
    container_name: serverless
    # command: yarn run start:dev
    #volumes:
      # - ./:/code
      # - ./node_modules:/code/node_modules
    ports:
      - 80:80
